package main

// enum ibv_mtu
const (
	IBV_MTU_256 = 1
	IBV_MTU_512 = 2
	IBV_MTU_1024 = 3
	IBV_MTU_2048 = 4
	IBV_MTU_4096 = 5
)

// enum ibv_qp_type
const (
	IBV_QPT_RC = 2
	IBV_QPT_UC = 3
	IBV_QPT_UD = 4
	IBV_QPT_RAW_PACKET = 8
	IBV_QPT_XRC_SEND = 9
	IBV_QPT_XRC_RECV = 10
)

// enum ibc_qp_attr_mask
const (
	IBV_QP_STATE	= 1 << iota
	IBV_QP_CUR_STATE
	IBV_QP_EN_SQD_ASYNC_NOTIFY
	IBV_QP_ACCESS_FLAGS
	IBV_QP_PKEY_INDEX
	IBV_QP_PORT
	IBV_QP_QKEY
	IBV_QP_AV
	IBV_QP_PATH_MTU
	IBV_QP_TIMEOUT
	IBV_QP_RETRY_CNT
	IBV_QP_RNR_RETRY
	IBV_QP_RQ_PSN
	IBV_QP_MAX_QP_RD_ATOMIC
	IBV_QP_ALT_PATH
	IBV_QP_MIN_RNR_TIMER
	IBV_QP_SQ_PSN
	IBV_QP_MAX_DEST_RD_ATOMIC
	IBV_QP_PATH_MIG_STATE
	IBV_QP_CAP
	IBV_QP_DEST_QPN
)


// enum ibv_qp_state
const (
	IBV_QPS_RESET = iota
	IBV_QPS_INIT
	IBV_QPS_RTR
	IBV_QPS_RTS
	IBV_QPS_SQD
	IBV_QPS_SQE
	IBV_QPS_ERR
	IBV_QPS_UNKNOWN
)

// enum ibv_access_flags
const (
	IBV_ACCESS_LOCAL_WRITE = 1 << iota
	IBV_ACCESS_REMOTE_WRITE
	IBV_ACCESS_REMOTE_READ
	IBV_ACCESS_REMOTE_ATOMIC
	IBV_ACCESS_MW_BIND
	IBV_ACCESS_ZERO_BASED
	IBV_ACCESS_ON_DEMAND
)

// enum ibv_wr_opcode
const  (
	IBV_WR_RDMA_WRITE = iota
	IBV_WR_RDMA_WRITE_WITH_IMM
	IBV_WR_SEND
	IBV_WR_SEND_WITH_IMM
	IBV_WR_RDMA_READ
	IBV_WR_ATOMIC_CMP_AND_SWP
	IBV_WR_ATOMIC_FETCH_AND_ADD
	IBV_WR_LOCAL_INV
	IBV_WR_BIND_MW
	IBV_WR_SEND_WITH_INV
)

// enum ibv_send_falgs

const (
	IBV_SEND_FENCE = 1 << iota
	IBV_SEND_SIGNALED
	IBV_SEND_SOLICITED
	IBV_SEND_INLINE
	IBV_SEND_IP_CSUM
)

